---

- name: create logstash local directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ logstash_conf_location }}"
    - "{{ logstash_data_location }}"

- name: write conf file
  become: true
  copy:
    content: "{{ logstash_conf_file_content }}"
    dest: "{{ logstash_conf_file }}"

- include_tasks: run_container.yml
